package com.meteorite.core.datasource.db.object;

/**
 * 数据库对象类型
 * 
 * @author wei_jc
 * @since 1.0.0
 */
public enum DBObjectType {
    ARGUMENT,
    CATEGORY,
    CHARSET,
    CLUSTER,
    COLUMN,
    CONSTRAINT,
    DATABASE,
    DATASET,
    DBLINK,
    DIMENSION,
    DIMENSION_ATTRIBUTE,
    DIMENSION_HIERARCHY,
    DIMENSION_LEVEL,
    DISKGROUP,
    DOMAIN,
    FUNCTION,
    GRANTED_PRIVILEGE,
    GRANTED_ROLE,
    INDEX,
    INDEXTYPE,
    JAVA_OBJECT,
    LOB,
    MATERIALIZED_VIEW,
    METHOD,
    MODEL,
    NESTED_TABLE,
    NESTED_TABLE_COLUMN,
    OPERATOR,
    OUTLINE,
    PACKAGE,
    PACKAGE_FUNCTION,
    PACKAGE_PROCEDURE,
    PACKAGE_TYPE,
    PACKAGE_BODY,
    PARTITION,
    PRIVILEGE,
    PROCEDURE,
    PROFILE,
    ROLLBACK_SEGMENT,
    ROLE,
    SCHEMA,
    SEQUENCE,
    SUBPARTITION,
    SYNONYM,
    TABLE,
    TABLESPACE,
    TRIGGER,
    TYPE,
    TYPE_ATTRIBUTE,
    TYPE_FUNCTION,
    TYPE_PROCEDURE,
    USER,
    VARRAY,
    VARRAY_TYPE,
    VIEW,


    CURSOR,
    PARAMETER,
    LABEL,
    SAVEPOINT,
    EXCEPTION,


    UNKNOWN,
    NONE,
    ANY
}
